version: '3'

services:
  terraform-backend-github:
    image: ghcr.io/andreygubarev/terraform-backend-github:latest
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - 8080:8080
    restart: unless-stopped
